# Generated by Django 4.1.7 on 2023-03-09 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='joined_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
